package com.jijing.fund.infrastructure.knowledge;
import com.jijing.fund.knowledge.port.AuthorizedDocumentProvider;import java.io.*;import java.net.*;import java.net.http.*;import java.time.Duration;import java.util.*;
public final class AllowlistedHttpDocumentProvider implements AuthorizedDocumentProvider {
 private static final Set<String>TYPES=Set.of("application/pdf","text/html","text/plain");private final Set<String>hosts;private final long maxBytes;private final HttpClient client;
 public AllowlistedHttpDocumentProvider(Set<String>hosts,long maxBytes){this.hosts=hosts.stream().map(v->v.toLowerCase(Locale.ROOT)).collect(java.util.stream.Collectors.toUnmodifiableSet());this.maxBytes=maxBytes;this.client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(3)).followRedirects(HttpClient.Redirect.NEVER).build();}
 public FetchedDocument fetch(URI uri){validate(uri);try{HttpRequest request=HttpRequest.newBuilder(uri).timeout(Duration.ofSeconds(20)).header("Accept","application/pdf,text/html,text/plain").GET().build();HttpResponse<InputStream>response=client.send(request,HttpResponse.BodyHandlers.ofInputStream());if(response.statusCode()<200||response.statusCode()>=300)throw new IllegalStateException("Authorized document source HTTP "+response.statusCode());long declared=response.headers().firstValueAsLong("Content-Length").orElse(-1);if(declared>maxBytes)throw new IllegalArgumentException("Remote document exceeds size limit");String type=response.headers().firstValue("Content-Type").orElse("").split(";",2)[0].trim().toLowerCase(Locale.ROOT);if(!TYPES.contains(type))throw new IllegalArgumentException("Remote document content type is not supported");byte[]content=readLimited(response.body());String path=uri.getPath();String file=path==null||path.endsWith("/")?"document":path.substring(path.lastIndexOf('/')+1);return new FetchedDocument(uri,file,type,content);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("Document fetch interrupted",e);}catch(IOException e){throw new IllegalStateException("Document fetch failed",e);}}
 private void validate(URI uri){if(uri==null||!"https".equalsIgnoreCase(uri.getScheme())||uri.getHost()==null)throw new IllegalArgumentException("Only allowlisted HTTPS document URLs are accepted");String host=uri.getHost().toLowerCase(Locale.ROOT);if(!hosts.contains(host))throw new IllegalArgumentException("Document source host is not allowlisted");try{for(InetAddress address:InetAddress.getAllByName(host))if(address.isAnyLocalAddress()||address.isLoopbackAddress()||address.isLinkLocalAddress()||address.isSiteLocalAddress())throw new IllegalArgumentException("Private network document sources are forbidden");}catch(UnknownHostException e){throw new IllegalArgumentException("Document source host cannot be resolved",e);}}
 private byte[]readLimited(InputStream input)throws IOException{try(input;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[]buffer=new byte[8192];long total=0;for(int n;(n=input.read(buffer))>=0;){total+=n;if(total>maxBytes)throw new IllegalArgumentException("Remote document exceeds size limit");out.write(buffer,0,n);}return out.toByteArray();}}
}
