package com.jijing.fund.infrastructure.knowledge;
import com.fasterxml.jackson.databind.*;import com.jijing.fund.knowledge.port.IndexGovernanceGateway;import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;
public final class ElasticsearchIndexGovernanceGateway implements IndexGovernanceGateway {
 private final URI base;private final String baseIndex,readAlias,writeAlias;private final ObjectMapper mapper;private final HttpClient client;private final Duration timeout;private final String authorization;
 public ElasticsearchIndexGovernanceGateway(String uri,String baseIndex,ObjectMapper mapper,String username,String password,String apiKey,Duration connect,Duration read){this.base=URI.create(uri.endsWith("/")?uri.substring(0,uri.length()-1):uri);this.baseIndex=baseIndex;this.readAlias=baseIndex+"_read";this.writeAlias=baseIndex+"_write";this.mapper=mapper;this.timeout=read==null?Duration.ofSeconds(30):read;this.client=HttpClient.newBuilder().connectTimeout(connect==null?Duration.ofSeconds(2):connect).build();if(apiKey!=null&&!apiKey.isBlank())authorization="ApiKey "+apiKey;else if(username!=null&&!username.isBlank())authorization="Basic "+Base64.getEncoder().encodeToString((username+":"+(password==null?"":password)).getBytes(StandardCharsets.UTF_8));else authorization=null;}
 public PreparedIndex rebuild(String rebuildId){String previous=currentIndex();String target=baseIndex+"_"+DateTimeFormatter.ofPattern("yyyyMMddHHmmss").withZone(ZoneOffset.UTC).format(Instant.now())+"_"+rebuildId.substring(0,8);JsonNode mappings=read("GET","/"+previous+"/_mapping",null).path(previous).path("mappings");send("PUT","/"+target,Map.of("mappings",mapper.convertValue(mappings,Map.class)));long expected=count(previous);JsonNode reindex=read("POST","/_reindex?wait_for_completion=true&refresh=true",Map.of("source",Map.of("index",previous),"dest",Map.of("index",target,"op_type","create"),"conflicts","proceed"));long indexed=count(target);Map<String,Object>report=new LinkedHashMap<>();report.put("expectedChunkCount",expected);report.put("indexedChunkCount",indexed);report.put("embeddingDimensions",mappingDimensions(mappings));report.put("mappingHash",Integer.toHexString(mappings.toString().hashCode()));report.put("versionConflicts",reindex.path("version_conflicts").asLong());report.put("failures",mapper.convertValue(reindex.path("failures"),List.class));return new PreparedIndex(readAlias,writeAlias,previous,target,expected,indexed,Map.copyOf(report));}
 public void activate(String read,String write,String previous,String target){switchAliases(read,write,previous,target);}
 public void rollback(String read,String write,String current,String previous){if(previous==null||previous.isBlank())throw new IllegalStateException("No previous index is available for rollback");switchAliases(read,write,current,previous);}
 private void switchAliases(String read,String write,String oldIndex,String newIndex){List<Object>actions=new ArrayList<>();if(hasAlias(read))actions.add(Map.of("remove",Map.of("index","*","alias",read,"must_exist",false)));if(hasAlias(write))actions.add(Map.of("remove",Map.of("index","*","alias",write,"must_exist",false)));actions.add(Map.of("add",Map.of("index",newIndex,"alias",read)));actions.add(Map.of("add",Map.of("index",newIndex,"alias",write,"is_write_index",true)));send("POST","/_aliases",Map.of("actions",actions));}
 private boolean hasAlias(String alias){HttpResponse<String>r=request("HEAD","/_alias/"+alias,null);return r.statusCode()==200;}
 private String currentIndex(){HttpResponse<String>r=request("GET","/_alias/"+readAlias,null);if(r.statusCode()==200){try{return mapper.readTree(r.body()).fieldNames().next();}catch(Exception e){throw new IllegalStateException("Invalid alias response",e);}}HttpResponse<String>baseResponse=request("HEAD","/"+baseIndex,null);if(baseResponse.statusCode()==200)return baseIndex;throw new IllegalStateException("No source index or read alias exists");}
 private long count(String index){return read("GET","/"+index+"/_count",null).path("count").asLong();}
 private int mappingDimensions(JsonNode mappings){return mappings.path("properties").path("embedding").path("dims").asInt();}
 private JsonNode read(String method,String path,Object body){try{return mapper.readTree(send(method,path,body));}catch(Exception e){throw new IllegalStateException("Invalid Elasticsearch governance response",e);}}
 private String send(String method,String path,Object body){HttpResponse<String>r=request(method,path,body);if(r.statusCode()<200||r.statusCode()>=300)throw new IllegalStateException("Elasticsearch governance HTTP "+r.statusCode()+": "+r.body().substring(0,Math.min(300,r.body().length())));return r.body();}
 private HttpResponse<String>request(String method,String path,Object body){try{HttpRequest.Builder b=HttpRequest.newBuilder(base.resolve(path)).timeout(timeout);if(authorization!=null)b.header("Authorization",authorization);String json=body==null?"":mapper.writeValueAsString(body);if(body!=null)b.header("Content-Type","application/json");b.method(method,json.isEmpty()?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json));return client.send(b.build(),HttpResponse.BodyHandlers.ofString());}catch(Exception e){throw new IllegalStateException("Elasticsearch governance request failed",e);}}
}
