package com.jijing.fund.infrastructure.knowledge;

import com.fasterxml.jackson.databind.*;
import com.jijing.fund.knowledge.api.KnowledgeSearchQuery;
import com.jijing.fund.knowledge.domain.*;
import com.jijing.fund.knowledge.port.DocumentSearchIndex;
import java.net.URI;
import java.net.http.*;
import java.time.*;
import java.util.*;

/** Elasticsearch REST adapter supporting BM25 and dense-vector kNN without paid RRF features. */
public final class ElasticsearchHttpDocumentSearchIndex implements DocumentSearchIndex {
    private final URI baseUri;private final String indexName,version,readTarget,writeTarget;private final int dimensions;private final ObjectMapper mapper;private final HttpClient client;private final String authorization;private final Duration readTimeout;
    public ElasticsearchHttpDocumentSearchIndex(String uri,String indexName,int dimensions,String version,ObjectMapper mapper){this(uri,indexName,dimensions,version,mapper,null,null,null,Duration.ofSeconds(2),Duration.ofSeconds(10),false);}
    public ElasticsearchHttpDocumentSearchIndex(String uri,String indexName,int dimensions,String version,ObjectMapper mapper,String username,String password,String apiKey,Duration connectTimeout,Duration readTimeout){this(uri,indexName,dimensions,version,mapper,username,password,apiKey,connectTimeout,readTimeout,true);}
    private ElasticsearchHttpDocumentSearchIndex(String uri,String indexName,int dimensions,String version,ObjectMapper mapper,String username,String password,String apiKey,Duration connectTimeout,Duration readTimeout,boolean aliases){if(indexName==null||!indexName.matches("[a-z0-9_-]+"))throw new IllegalArgumentException("Invalid Elasticsearch index name");this.baseUri=URI.create(uri.endsWith("/")?uri.substring(0,uri.length()-1):uri);this.indexName=indexName;this.dimensions=dimensions;this.version=version;this.mapper=mapper;Duration connect=connectTimeout==null?Duration.ofSeconds(2):connectTimeout;this.readTimeout=readTimeout==null?Duration.ofSeconds(10):readTimeout;this.client=HttpClient.newBuilder().connectTimeout(connect).build();if(apiKey!=null&&!apiKey.isBlank())this.authorization="ApiKey "+apiKey;else if(username!=null&&!username.isBlank())this.authorization="Basic "+Base64.getEncoder().encodeToString((username+":"+(password==null?"":password)).getBytes(java.nio.charset.StandardCharsets.UTF_8));else this.authorization=null;ensureIndex();if(aliases){ensureAliases();this.readTarget=indexName+"_read";this.writeTarget=indexName+"_write";}else{this.readTarget=indexName;this.writeTarget=indexName;}}
    @Override public String indexVersion(){return indexName+":"+version;}
    @Override public void index(List<IndexedChunk>chunks){if(chunks.isEmpty())return;StringBuilder body=new StringBuilder();for(IndexedChunk value:chunks){if(value.embedding()==null||value.embedding().length!=dimensions)throw new IllegalStateException("EMBEDDING_DIMENSION_MISMATCH before Elasticsearch write");try{body.append(mapper.writeValueAsString(Map.of("index",Map.of("_index",writeTarget,"_id",value.chunk().chunkId())))).append('\n');body.append(mapper.writeValueAsString(source(value))).append('\n');}catch(Exception ex){throw new IllegalStateException("Cannot serialize Elasticsearch bulk request",ex);}}String response=send("POST","/_bulk?refresh=wait_for",body.toString(),"application/x-ndjson");try{JsonNode root=mapper.readTree(response);if(root.path("errors").asBoolean(false))throw new IllegalStateException("Elasticsearch bulk request contains partial failures");}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw new IllegalStateException("Invalid Elasticsearch bulk response",ex);}}
    @Override public void activate(String documentId,String versionId){try{Map<String,Object>bool=Map.of("filter",List.of(Map.of("term",Map.of("document_id",documentId))),"must_not",List.of(Map.of("term",Map.of("version_id",versionId))));send("POST","/"+writeTarget+"/_delete_by_query?refresh=true",mapper.writeValueAsString(Map.of("query",Map.of("bool",bool))),"application/json");}catch(Exception ex){throw new IllegalStateException("Cannot activate Elasticsearch document version",ex);}}
    @Override public List<RetrievedChunk> lexicalSearch(KnowledgeSearchQuery query,int topK){Map<String,Object>bool=new LinkedHashMap<>();bool.put("must",List.of(Map.of("match",Map.of("content",Map.of("query",query.query())))));List<Object>filters=filters(query);if(!filters.isEmpty())bool.put("filter",filters);Map<String,Object>body=Map.of("size",topK,"query",Map.of("bool",bool),"_source",true);return search(body,"bm25");}
    @Override public List<RetrievedChunk> vectorSearch(KnowledgeSearchQuery query,float[]embedding,int topK){Map<String,Object>knn=new LinkedHashMap<>();knn.put("field","embedding");knn.put("query_vector",floats(embedding));knn.put("k",topK);knn.put("num_candidates",Math.max(100,topK*4));List<Object>filters=filters(query);if(!filters.isEmpty())knn.put("filter",Map.of("bool",Map.of("filter",filters)));return search(Map.of("size",topK,"knn",knn,"_source",true),"vector");}
    private void ensureIndex(){HttpResponse<String>head=request("HEAD","/"+indexName,"",null);if(head.statusCode()==200)return;if(head.statusCode()!=404)throw new IllegalStateException("Elasticsearch index check failed: HTTP "+head.statusCode());Map<String,Object>properties=new LinkedHashMap<>();for(String keyword:List.of("chunk_id","document_id","version_id","fund_codes","document_type","content_sha256","embedding_version","chunking_version","source_name"))properties.put(keyword,Map.of("type","keyword"));properties.put("published_date",Map.of("type","date"));properties.put("heading_path",Map.of("type","text"));properties.put("page_start",Map.of("type","integer"));properties.put("page_end",Map.of("type","integer"));properties.put("chunk_order",Map.of("type","integer"));properties.put("token_count",Map.of("type","integer"));properties.put("document_title",Map.of("type","text"));properties.put("source_uri",Map.of("type","keyword","ignore_above",2048));properties.put("content",Map.of("type","text"));properties.put("embedding",Map.of("type","dense_vector","dims",dimensions,"index",true,"similarity","cosine"));try{send("PUT","/"+indexName,mapper.writeValueAsString(Map.of("mappings",Map.of("properties",properties))),"application/json");}catch(Exception ex){throw new IllegalStateException("Cannot create Elasticsearch index",ex);}}
    private void ensureAliases(){String read=indexName+"_read",write=indexName+"_write";boolean hasRead=request("HEAD","/_alias/"+read,"",null).statusCode()==200;boolean hasWrite=request("HEAD","/_alias/"+write,"",null).statusCode()==200;if(hasRead&&hasWrite)return;List<Object>actions=new ArrayList<>();if(!hasRead)actions.add(Map.of("add",Map.of("index",indexName,"alias",read)));if(!hasWrite)actions.add(Map.of("add",Map.of("index",indexName,"alias",write,"is_write_index",true)));try{send("POST","/_aliases",mapper.writeValueAsString(Map.of("actions",actions)),"application/json");}catch(Exception e){throw new IllegalStateException("Cannot initialize Elasticsearch aliases",e);}}
    private Map<String,Object>source(IndexedChunk value){DocumentChunk c=value.chunk();Map<String,Object>m=new LinkedHashMap<>();m.put("chunk_id",c.chunkId());m.put("document_id",c.documentId());m.put("version_id",c.versionId());m.put("fund_codes",c.fundCodes());m.put("document_type",c.documentType().name());m.put("published_date",c.publishedDate()==null?null:c.publishedDate().toString());m.put("heading_path",c.headingPath());m.put("page_start",c.pageStart());m.put("page_end",c.pageEnd());m.put("chunk_order",c.chunkOrder());m.put("token_count",c.tokenCount());m.put("document_title",c.documentTitle());m.put("content",c.content());m.put("content_sha256",c.contentSha256());m.put("chunking_version",c.chunkingVersion());m.put("embedding_version",value.embeddingVersion());m.put("source_name",c.sourceName());m.put("source_uri",c.sourceUri());m.put("embedding",floats(value.embedding()));return m;}
    private List<Object>filters(KnowledgeSearchQuery q){List<Object>f=new ArrayList<>();if(!q.fundCodes().isEmpty())f.add(Map.of("terms",Map.of("fund_codes",q.fundCodes())));if(!q.documentTypes().isEmpty())f.add(Map.of("terms",Map.of("document_type",q.documentTypes().stream().map(Enum::name).toList())));if(q.publishedAfter()!=null||q.publishedBefore()!=null){Map<String,Object>range=new LinkedHashMap<>();if(q.publishedAfter()!=null)range.put("gte",q.publishedAfter().toString());if(q.publishedBefore()!=null)range.put("lte",q.publishedBefore().toString());f.add(Map.of("range",Map.of("published_date",range)));}return f;}
    private List<RetrievedChunk>search(Map<String,Object>body,String channel){try{JsonNode root=mapper.readTree(send("POST","/"+readTarget+"/_search",mapper.writeValueAsString(body),"application/json"));List<RetrievedChunk>result=new ArrayList<>();int rank=1;for(JsonNode hit:root.path("hits").path("hits")){JsonNode s=hit.path("_source");DocumentChunk c=new DocumentChunk(text(s,"chunk_id"),text(s,"document_id"),text(s,"version_id"),text(s,"content"),text(s,"heading_path"),s.path("page_start").asInt(),s.path("page_end").asInt(),s.path("chunk_order").asInt(),s.path("token_count").asInt(),text(s,"chunking_version"),text(s,"content_sha256"),stringSet(s.path("fund_codes")),FundDocumentType.valueOf(text(s,"document_type")),text(s,"document_title"),date(s,"published_date"),text(s,"source_name"),nullableText(s,"source_uri"));result.add(new RetrievedChunk(c,hit.path("_score").asDouble(),rank++,Set.of(channel)));}return result;}catch(Exception ex){throw new IllegalStateException("Elasticsearch search failed",ex);}}
    private String send(String method,String path,String body,String contentType){HttpResponse<String>response=request(method,path,body,contentType);if(response.statusCode()<200||response.statusCode()>=300)throw new IllegalStateException("Elasticsearch HTTP "+response.statusCode()+": "+response.body().substring(0,Math.min(300,response.body().length())));return response.body();}
    private HttpResponse<String>request(String method,String path,String body,String contentType){try{HttpRequest.Builder builder=HttpRequest.newBuilder(baseUri.resolve(path)).timeout(readTimeout);if(contentType!=null)builder.header("Content-Type",contentType);if(authorization!=null)builder.header("Authorization",authorization);builder.method(method,body==null||body.isEmpty()?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(body));return client.send(builder.build(),HttpResponse.BodyHandlers.ofString());}catch(Exception ex){throw new IllegalStateException("Elasticsearch request failed",ex);}}
    private List<Float>floats(float[]values){List<Float>r=new ArrayList<>(values.length);for(float v:values)r.add(v);return r;}
    private Set<String>stringSet(JsonNode node){Set<String>r=new HashSet<>();node.forEach(v->r.add(v.asText()));return r;}
    private String text(JsonNode n,String f){return n.path(f).asText();}private String nullableText(JsonNode n,String f){return n.path(f).isNull()||n.path(f).isMissingNode()?null:n.path(f).asText();}private LocalDate date(JsonNode n,String f){String v=nullableText(n,f);return v==null?null:LocalDate.parse(v);}
}
