package com.jijing.fund.infrastructure.knowledge;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.jijing.fund.knowledge.api.IndexRebuildView;import com.jijing.fund.knowledge.port.IndexRebuildRepository;import java.sql.*;import java.time.Instant;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;
public class JdbcIndexRebuildRepository implements IndexRebuildRepository {
 private final JdbcTemplate jdbc;private final ObjectMapper mapper;public JdbcIndexRebuildRepository(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
 public void create(String id,String alias,String previous,String target,String embedding,String chunking,Instant now){jdbc.update("INSERT INTO knowledge_index_rebuild(rebuild_id,source_alias,previous_index,target_index,embedding_version,chunking_version,status,created_at) VALUES(?,?,?,?,?,?,?,?)",id,alias,previous,target,embedding,chunking,"BUILDING",ts(now));}
 public void ready(String id,long expected,long indexed,Map<String,Object>report,Instant now){jdbc.update("UPDATE knowledge_index_rebuild SET status='READY_TO_ACTIVATE',expected_chunk_count=?,indexed_chunk_count=?,validation_report_json=CAST(? AS JSON) WHERE rebuild_id=?",expected,indexed,json(report),id);}
 public void status(String id,String expected,String status,Instant now){int changed=jdbc.update("UPDATE knowledge_index_rebuild SET status=?,completed_at=? WHERE rebuild_id=? AND status=?",status,ts(now),id,expected);if(changed!=1)throw new IllegalStateException("Concurrent or invalid index rebuild transition");}
 public void fail(String id,String code,Map<String,Object>report,Instant now){jdbc.update("UPDATE knowledge_index_rebuild SET status='FAILED',error_code=?,validation_report_json=CAST(? AS JSON),completed_at=? WHERE rebuild_id=?",code,json(report),ts(now),id);}
 public IndexRebuildView find(String id){List<IndexRebuildView>rows=jdbc.query("SELECT * FROM knowledge_index_rebuild WHERE rebuild_id=?",(rs,n)->new IndexRebuildView(rs.getString("rebuild_id"),rs.getString("source_alias"),rs.getString("previous_index"),rs.getString("target_index"),rs.getString("embedding_version"),rs.getString("chunking_version"),rs.getString("status"),(Long)rs.getObject("expected_chunk_count"),rs.getLong("indexed_chunk_count"),read(rs.getString("validation_report_json")),rs.getString("error_code"),instant(rs.getTimestamp("created_at")),instant(rs.getTimestamp("completed_at"))),id);return rows.stream().findFirst().orElseThrow(()->new IllegalArgumentException("Index rebuild not found"));}
 private String json(Object v){try{return mapper.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException("Cannot serialize index report",e);}}private Map<String,Object>read(String v){try{return v==null?Map.of():mapper.readValue(v,new TypeReference<>(){});}catch(Exception e){return Map.of("parseError",true);}}private Timestamp ts(Instant v){return Timestamp.from(v);}private Instant instant(Timestamp v){return v==null?null:v.toInstant();}
}
