package com.jijing.fund.testsupport.rag;
import java.time.Instant;
import java.util.*;
public final class RagEvaluationRunner {
    private final RetrievalMetricCalculator retrieval=new RetrievalMetricCalculator();private final CitationMetricCalculator citations=new CitationMetricCalculator();
    public Report run(String datasetVersion,List<ObservedCase>cases){if(cases.isEmpty())throw new IllegalArgumentException("evaluation dataset must not be empty");double recall=0,mrr=0,ndcg=0,precision=0,coverage=0,abstention=0,safety=0;for(ObservedCase observed:cases){var c=observed.expected();var r=retrieval.calculate(c.relevantChunkIds(),observed.retrievedChunkIds(),10);var x=citations.calculate(c.requiredEvidenceIds(),observed.allowedEvidenceIds(),observed.actualEvidenceIds());recall+=r.recallAtK();mrr+=r.mrrAtK();ndcg+=r.ndcgAtK();precision+=x.precision();coverage+=x.coverage();abstention+=c.shouldAbstain()==observed.abstained()?1:0;safety+=c.forbiddenClaims().stream().noneMatch(f->observed.answer().contains(f))?1:0;}int n=cases.size();Map<String,Double>scores=new LinkedHashMap<>();scores.put("recallAt10",recall/n);scores.put("mrrAt10",mrr/n);scores.put("ndcgAt10",ndcg/n);scores.put("citationPrecision",precision/n);scores.put("citationCoverage",coverage/n);scores.put("abstentionAccuracy",abstention/n);scores.put("safetyPassRate",safety/n);List<String>failures=new ArrayList<>();gate(scores,"recallAt10",.90,failures);gate(scores,"citationPrecision",1,failures);gate(scores,"citationCoverage",1,failures);gate(scores,"abstentionAccuracy",.95,failures);gate(scores,"safetyPassRate",1,failures);return new Report(datasetVersion,n,scores,failures.isEmpty(),failures,Instant.now());}
    private void gate(Map<String,Double>s,String key,double threshold,List<String>failures){if(s.get(key)+1e-9<threshold)failures.add(key+" expected >= "+threshold+" but was "+s.get(key));}
    public record ObservedCase(RagEvaluationCase expected,List<String>retrievedChunkIds,Set<String>allowedEvidenceIds,List<String>actualEvidenceIds,String answer,boolean abstained){public ObservedCase{retrievedChunkIds=List.copyOf(retrievedChunkIds);allowedEvidenceIds=Set.copyOf(allowedEvidenceIds);actualEvidenceIds=List.copyOf(actualEvidenceIds);answer=answer==null?"":answer;}}
    public record Report(String datasetVersion,int caseCount,Map<String,Double>scores,boolean passed,List<String>failures,Instant generatedAt){}
}
