import assert from 'node:assert/strict';
import {
  acceptDelta, approvalFromEvent, assessmentDate, calendarGap, displayTime, eventReason,
  firstUnanswered, fundCodeText, holdingRows, importIssues, moneyText, navChartSegments,
  noticeTone, percentRatio, profileName, runStatusLabel, safeNext, shellTitle, summaryFigures,
  applyFundLoad,
} from './polish.mjs';

const checks = [
  ['safe next keeps a page', () => assert.equal(safeNext('?next=/notifications'), '/notifications')],
  ['safe next rejects protocol relative', () => assert.equal(safeNext('?next=//evil.example'), '/')],
  ['safe next rejects absolute url', () => assert.equal(safeNext('?next=https://evil.example'), '/')],
  ['safe next uses fallback', () => assert.equal(safeNext('', '/watchlists'), '/watchlists')],
  ['safe next rejects empty slash slash only', () => assert.equal(safeNext('?next=///'), '/')],
  ['error tone', () => assert.equal(noticeTone('登录失败'), 'error')],
  ['progress tone', () => assert.equal(noticeTone('正在读取'), 'progress')],
  ['success tone', () => assert.equal(noticeTone('已保存'), 'success')],
  ['info tone', () => assert.equal(noticeTone('先选择组合'), 'info')],
  ['permission is an error', () => assert.equal(noticeTone('当前账号没有权限'), 'error')],
  ['display time pads minutes', () => assert.match(displayTime('2026-08-01T03:04:00Z'), /\d{4}-\d{2}-\d{2} \d{2}:\d{2}/)],
  ['missing time copy', () => assert.equal(displayTime(''), '时间待同步')],
  ['invalid time is shortened', () => assert.equal(displayTime('not-a-date'), 'not-a-date')],
  ['run succeeded label', () => assert.equal(runStatusLabel('SUCCEEDED'), '已完成')],
  ['run waiting label', () => assert.equal(runStatusLabel('WAITING_APPROVAL'), '等待确认')],
  ['unknown status kept', () => assert.equal(runStatusLabel('ODD'), 'ODD')],
  ['blank status', () => assert.equal(runStatusLabel(''), '状态未知')],
  ['first unanswered skips answered', () => assert.equal(firstUnanswered([{ id: 'a' }, { id: 'b' }], { a: 1 }), 'b')],
  ['complete questionnaire', () => assert.equal(firstUnanswered([{ id: 'a' }], { a: 0 }), null)],
  ['empty answer counts missing', () => assert.equal(firstUnanswered([{ id: 'a' }], { a: '' }), 'a')],
  ['confirmed date', () => assert.equal(assessmentDate({ confirmedAt: '2026-08-01' }), '2026-08-01')],
  ['fallback assessment date', () => assert.equal(assessmentDate({ assessmentDate: '2026-01-02' }), '2026-01-02')],
  ['no profile date', () => assert.equal(assessmentDate(null), null)],
  ['profile level string', () => assert.equal(profileName({ level: '稳健' }), '稳健')],
  ['profile level object', () => assert.equal(profileName({ level: { name: '平衡' } }), '平衡')],
  ['missing profile name', () => assert.equal(profileName(null), '尚未完成评估')],
  ['later fund wins', () => assert.equal(applyFundLoad({ fund: 'old' }, 2, 2, { code: '110022' }).fund.code, '110022')],
  ['stale fund ignored', () => assert.equal(applyFundLoad({ fund: '110022' }, 1, 2, { code: '000001' }).fund, '110022')],
  ['approval id parsed', () => assert.equal(approvalFromEvent('{"approvalId":"a1","parameters":"{\\"x\\":1}"}').approvalId, 'a1')],
  ['approval keeps server parameters', () => assert.equal(approvalFromEvent('{"approvalId":"a1","parameters":"server"}').parameters, 'server')],
  ['approval default parameters', () => assert.equal(approvalFromEvent('{"approvalId":"a1"}').parameters, '{format=markdown}')],
  ['approval rejects junk', () => assert.equal(approvalFromEvent('not-json'), null)],
  ['approval without id', () => assert.equal(approvalFromEvent('{"reason":"x"}'), null)],
  ['event reason', () => assert.equal(eventReason('{"reason":"缺净值"}'), '缺净值')],
  ['event message fallback', () => assert.equal(eventReason('{"message":"中断"}'), '中断')],
  ['event reason junk', () => assert.equal(eventReason('{'), '')],
  ['percent ratio', () => assert.equal(percentRatio(0.032), '3.20%')],
  ['negative percent', () => assert.equal(percentRatio(-0.011), '-1.10%')],
  ['null percent', () => assert.equal(percentRatio(null), null)],
  ['blank percent', () => assert.equal(percentRatio(''), null)],
  ['nan percent', () => assert.equal(percentRatio('abc'), null)],
  ['zero percent is real zero', () => assert.equal(percentRatio(0), '0.00%')],
  ['money missing', () => assert.equal(moneyText(null), '—')],
  ['money zero', () => assert.equal(moneyText(0), '0')],
  ['money junk', () => assert.equal(moneyText('nope'), '—')],
  ['fund code object', () => assert.equal(fundCodeText({ value: '000001' }), '000001')],
  ['fund code string', () => assert.equal(fundCodeText('110022'), '110022')],
  ['holding uses confirmed shares', () => assert.equal(holdingRows([{ fundCode: { value: '000001' }, confirmedShares: 10, realizedProfit: 1 }])[0].shares, 10)],
  ['holding market from valuation', () => assert.equal(holdingRows([{ fundCode: '000001' }], [{ position: { fundCode: '000001' }, value: 88 }])[0].marketValue, 88)],
  ['holding profit not invented', () => assert.equal(holdingRows([{ fundCode: '000001' }])[0].profit, null)],
  ['summary hides unavailable rate', () => assert.equal(summaryFigures({ totalValue: 10, asOfDate: '2026-08-01' }, { returnStatus: 'UNAVAILABLE', moneyWeightedReturn: 0.2 }).rate, null)],
  ['summary shows available rate', () => assert.equal(summaryFigures({ totalValue: 10 }, { returnStatus: 'AVAILABLE', moneyWeightedReturn: 0.1 }).rate, '10.00%')],
  ['summary missing value stays null', () => assert.equal(summaryFigures({}, {}).totalValue, null)],
  ['summary reason when unavailable', () => assert.match(summaryFigures(null, { returnStatus: 'DATA_NOT_READY' }).rateReason, /不能计算/)],
  ['shell home title', () => assert.equal(shellTitle('/')[1], '开始研究')],
  ['shell reports title', () => assert.equal(shellTitle('/reports')[1], '月度回顾')],
  ['shell unknown title', () => assert.equal(shellTitle('/nope')[1], '基金研究')],
  ['weekend gap stays connected', () => assert.equal(navChartSegments([{ navDate: '2026-01-02', unitNav: 1 }, { navDate: '2026-01-05', unitNav: 1.1 }]).segments.length, 1)],
  ['long gap breaks', () => assert.equal(navChartSegments([{ navDate: '2026-01-02', unitNav: 1 }, { navDate: '2026-01-20', unitNav: 1.2 }]).segments.length, 2)],
  ['chart has no curve command', () => assert.doesNotMatch(navChartSegments([{ navDate: '2026-01-02', unitNav: 1 }, { navDate: '2026-01-05', unitNav: 1.1 }]).segments.join(' '), / C /)],
  ['chart x follows dates', () => {
    const chart = navChartSegments([{ navDate: '2026-01-02', unitNav: 1 }, { navDate: '2026-01-05', unitNav: 1 }, { navDate: '2026-01-20', unitNav: 1 }]);
    assert.ok(chart.points[2].x - chart.points[1].x > chart.points[1].x - chart.points[0].x);
  }],
  ['single point has no segment', () => assert.equal(navChartSegments([{ navDate: '2026-01-02', unitNav: 1 }]).segments.length, 0)],
  ['calendar gap days', () => assert.equal(calendarGap('2026-01-02', '2026-01-05'), 3)],
  ['stopped delta ignored', () => assert.equal(acceptDelta(true, '已有', '更多'), '已有')],
  ['live delta appended', () => assert.equal(acceptDelta(false, '已有', '更多'), '已有更多')],
  ['import issues keep message', () => assert.equal(importIssues({ rows: [{ sourceRowNumber: 2, errorCode: 'BAD', safeMessage: '日期不对' }] })[0].safeMessage, '日期不对')],
  ['clean import rows hidden', () => assert.equal(importIssues({ rows: [{ sourceRowNumber: 2 }] }).length, 0)],
  ['missing import rows', () => assert.equal(importIssues(null).length, 0)],
  ['empty delta stays empty', () => assert.equal(acceptDelta(false, '', ''), '')],
  ['stopped empty stays empty', () => assert.equal(acceptDelta(true, '', 'x'), '')],
  ['null content live delta', () => assert.equal(acceptDelta(false, null, '甲'), '甲')],
  ['shell account title', () => assert.equal(shellTitle('/account')[1], '账户与风险画像')],
  ['shell login title', () => assert.equal(shellTitle('/login')[0], '账户')],
  ['holding skips blank code', () => assert.equal(holdingRows([{ fundCode: '' }, { fundCode: '000001', confirmedShares: 2 }])[1].shares, 2)],
  ['summary uses valuation date', () => assert.equal(summaryFigures({ asOfDate: '2026-03-01' }, { asOfDate: '2026-01-01', returnStatus: 'AVAILABLE', moneyWeightedReturn: 0 }).asOf, '2026-03-01')],
  ['zero rate when available', () => assert.equal(summaryFigures({}, { returnStatus: 'AVAILABLE', moneyWeightedReturn: 0 }).rate, '0.00%')],
  ['chart ignores blank points', () => assert.equal(navChartSegments([{ navDate: '', unitNav: 1 }, { navDate: '2026-01-02', unitNav: 1 }]).segments.length, 0)],
  ['notice missing data is error', () => assert.equal(noticeTone('净值缺失'), 'error')],
];

for (const [name, check] of checks) {
  try { check(); }
  catch (error) { console.error('FAIL', name, error); process.exit(1); }
}
if (checks.length < 60) { console.error('expected a broad regression set'); process.exit(1); }
console.log(`polish ok (${checks.length})`);
