package com.jijing.fund.infrastructure.security;

import com.jijing.fund.domain.identity.UserId;import com.jijing.fund.domain.model.FundCode;import com.jijing.fund.domain.portfolio.*;
import java.math.BigDecimal;import java.sql.Timestamp;import java.time.*;import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;

public class JdbcPortfolioRepository implements PortfolioRepository {
    private final JdbcTemplate jdbc;public JdbcPortfolioRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
    @Override public List<UserPortfolio> findByOwner(UserId owner){return jdbc.query("SELECT * FROM user_portfolio WHERE owner_user_id=? ORDER BY updated_at DESC",this::portfolio,owner.value());}
    @Override public Optional<UserPortfolio> findByIdAndOwner(PortfolioId id,UserId owner){return jdbc.query("SELECT * FROM user_portfolio WHERE portfolio_id=? AND owner_user_id=?",this::portfolio,id.value(),owner.value()).stream().findFirst();}
    @Override public void savePortfolio(UserPortfolio p){jdbc.update("INSERT INTO user_portfolio(portfolio_id,owner_user_id,display_name,currency,status,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",p.portfolioId().value(),p.ownerUserId().value(),p.displayName(),p.currency(),p.status().name(),p.version(),ts(p.createdAt()),ts(p.updatedAt()));}
    @Override public boolean updateVersion(PortfolioId id,UserId owner,long expected,long next){return jdbc.update("UPDATE user_portfolio SET version=?,updated_at=? WHERE portfolio_id=? AND owner_user_id=? AND version=?",next,ts(Instant.now()),id.value(),owner.value(),expected)>0;}
    @Override public Optional<FundTransaction> findByIdempotency(UserId owner,PortfolioId id,String key){return jdbc.query("SELECT * FROM fund_transaction WHERE owner_user_id=? AND portfolio_id=? AND idempotency_key=?",this::transaction,owner.value(),id.value(),key).stream().findFirst();}
    @Override public Optional<FundTransaction> findTransaction(UserId owner,PortfolioId id,String tx){return jdbc.query("SELECT * FROM fund_transaction WHERE owner_user_id=? AND portfolio_id=? AND transaction_id=?",this::transaction,owner.value(),id.value(),tx).stream().findFirst();}
    @Override public boolean hasReversal(UserId owner,String original){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM fund_transaction WHERE owner_user_id=? AND reverses_transaction_id=?",Integer.class,owner.value(),original);return n!=null&&n>0;}
    @Override public void appendTransaction(FundTransaction t){jdbc.update("INSERT INTO fund_transaction(transaction_id,portfolio_id,owner_user_id,fund_code,transaction_type,trade_date,confirm_date,shares,gross_amount,fee,confirmed_nav,currency,source,idempotency_key,reverses_transaction_id,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",t.transactionId(),t.portfolioId().value(),t.ownerUserId().value(),t.fundCode().value(),t.transactionType().name(),t.tradeDate(),t.confirmDate(),t.shares(),t.grossAmount(),t.fee(),t.confirmedNav(),t.currency(),t.source(),t.idempotencyKey(),t.reversesTransactionId(),ts(t.createdAt()),t.ownerUserId().value());}
    @Override public List<FundTransaction> findTransactions(PortfolioId id,UserId owner){return jdbc.query("SELECT * FROM fund_transaction WHERE portfolio_id=? AND owner_user_id=? ORDER BY confirm_date,transaction_id",this::transaction,id.value(),owner.value());}
    @Override public void saveImportBatch(ImportBatch batch){
        jdbc.update("INSERT INTO portfolio_import_batch(batch_id,portfolio_id,owner_user_id,file_sha256,file_name,status,total_rows,valid_rows,invalid_rows,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)",batch.batchId(),batch.portfolioId().value(),batch.ownerUserId().value(),batch.fileSha256(),batch.fileName(),batch.status().name(),batch.totalRows(),batch.validRows(),batch.invalidRows(),ts(batch.createdAt()));
        for(ImportRow row:batch.rows())jdbc.update("INSERT INTO portfolio_import_row(batch_id,source_row_number,raw_json,error_code,safe_message) VALUES(?,?,?,?,?)",batch.batchId(),row.sourceRowNumber(),row.rawJson(),row.errorCode(),row.safeMessage());
    }
    @Override public Optional<ImportBatch> findImportBatch(UserId owner,PortfolioId id,String batchId){
        var batches=jdbc.query("SELECT * FROM portfolio_import_batch WHERE batch_id=? AND owner_user_id=? AND portfolio_id=?",this::batch,batchId,owner.value(),id.value());
        return batches.stream().findFirst().map(b->{var rows=jdbc.query("SELECT * FROM portfolio_import_row WHERE batch_id=? ORDER BY source_row_number",this::row,b.batchId());return new ImportBatch(b.batchId(),b.portfolioId(),b.ownerUserId(),b.fileSha256(),b.fileName(),b.status(),b.totalRows(),b.validRows(),b.invalidRows(),b.createdAt(),b.committedAt(),rows);});
    }
    @Override public void markImportCommitted(String batchId){jdbc.update("UPDATE portfolio_import_batch SET status=?,committed_at=? WHERE batch_id=?",ImportBatchStatus.COMMITTED.name(),ts(Instant.now()),batchId);}
    @Override public void deleteImportBatch(String batchId){jdbc.update("DELETE FROM portfolio_import_row WHERE batch_id=?",batchId);jdbc.update("UPDATE portfolio_import_batch SET status=? WHERE batch_id=?",ImportBatchStatus.DELETED.name(),batchId);}
    @Override public void replacePositionSnapshots(PortfolioId portfolioId,UserId owner,LocalDate asOf,List<FundPosition> positions,String inputHash){
        jdbc.update("DELETE FROM fund_position_snapshot WHERE portfolio_id=? AND owner_user_id=?",portfolioId.value(),owner.value());
        Instant now=Instant.now();
        for(FundPosition p:positions)jdbc.update("INSERT INTO fund_position_snapshot(snapshot_id,portfolio_id,owner_user_id,fund_code,as_of_date,confirmed_shares,remaining_cost,realized_profit,cash_dividend,input_hash,algorithm_version,coverage_status,calculated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),portfolioId.value(),owner.value(),p.fundCode().value(),asOf,p.confirmedShares(),p.remainingCost(),p.realizedProfit(),p.accumulatedCashDividend(),inputHash,"portfolio-position-v1","AVAILABLE",ts(now));
    }
    @Override public void deletePositionSnapshots(PortfolioId portfolioId,UserId owner){jdbc.update("DELETE FROM fund_position_snapshot WHERE portfolio_id=? AND owner_user_id=?",portfolioId.value(),owner.value());}
    @Override public int countPositionSnapshots(PortfolioId portfolioId,UserId owner){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM fund_position_snapshot WHERE portfolio_id=? AND owner_user_id=?",Integer.class,portfolioId.value(),owner.value());return n==null?0:n;}
    private UserPortfolio portfolio(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new UserPortfolio(new PortfolioId(r.getString("portfolio_id")),new UserId(r.getString("owner_user_id")),r.getString("display_name"),r.getString("currency"),PortfolioStatus.valueOf(r.getString("status")),r.getLong("version"),instant(r.getTimestamp("created_at")),instant(r.getTimestamp("updated_at")));}
    private FundTransaction transaction(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new FundTransaction(r.getString("transaction_id"),new PortfolioId(r.getString("portfolio_id")),new UserId(r.getString("owner_user_id")),new FundCode(r.getString("fund_code")),TransactionType.valueOf(r.getString("transaction_type")),r.getObject("trade_date",LocalDate.class),r.getObject("confirm_date",LocalDate.class),r.getBigDecimal("shares"),r.getBigDecimal("gross_amount"),r.getBigDecimal("fee"),r.getBigDecimal("confirmed_nav"),r.getString("currency"),r.getString("source"),r.getString("idempotency_key"),r.getString("reverses_transaction_id"),instant(r.getTimestamp("created_at")));}
    private ImportBatch batch(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new ImportBatch(r.getString("batch_id"),new PortfolioId(r.getString("portfolio_id")),new UserId(r.getString("owner_user_id")),r.getString("file_sha256"),r.getString("file_name"),ImportBatchStatus.valueOf(r.getString("status")),r.getInt("total_rows"),r.getInt("valid_rows"),r.getInt("invalid_rows"),instant(r.getTimestamp("created_at")),r.getTimestamp("committed_at")==null?null:instant(r.getTimestamp("committed_at")),List.of());}
    private ImportRow row(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new ImportRow(r.getInt("source_row_number"),r.getString("raw_json"),r.getString("error_code"),r.getString("safe_message"));}
    private static Timestamp ts(Instant v){return Timestamp.from(v);}private static Instant instant(Timestamp v){return v.toInstant();}
}
