package com.jijing.fund.agent.orchestration;

import com.jijing.fund.agent.api.EvidenceReference;
import com.jijing.fund.agent.exception.AgentEvidenceViolationException;
import java.time.LocalDate;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

class FundAgentCitationPolicyTest {
    private final FundAgentCitationPolicy policy=new FundAgentCitationPolicy();
    @Test void appendsPageAwareCitationWhenModelOmittedIt(){var evidence=EvidenceReference.document("DOC:d:v:c","000001","upload","d","v","c","季度报告",LocalDate.of(2026,6,30),7,8,"投资策略","原文","https://example.test");assertThat(policy.validateAndRepair("基金经理强调控制风险。",List.of(evidence))).contains("DOC:d:v:c").contains("第7-8页");}
    @Test void rejectsInventedCitation(){assertThatThrownBy(()->policy.validateAndRepair("依据 DOC:fake:v:c",List.of())).isInstanceOf(AgentEvidenceViolationException.class);}
    @Test void replacesInventedCitationWithCurrentEvidence(){var evidence=new EvidenceReference("ev-fund-1","FUND_PROFILE","000001",null,null,null,"Eastmoney",null,null,null);String answer=policy.validateAndRepair("基金代码为 000001【ev-fake】。",List.of(evidence));assertThat(answer).contains("ev-fund-1").doesNotContain("ev-fake");}
    @Test void acceptsCitationNextToMarkdownPunctuation(){var evidence=new EvidenceReference("ev-realtime-50d1d73c-6b89-46f2-a281-9cc39e522c1b","FUND_REALTIME_QUOTE","004069",null,null,null,"eastmoney-push2",null,null,null);String answer=policy.validateAndRepair("| **涨跌幅** | **+0.29%** | ev-realtime-50d1d73c-6b89-46f2-a281-9cc39e522c1b|\n",List.of(evidence));assertThat(answer).contains(evidence.evidenceId());}
    @Test void doesNotTreatMarkdownRuleAsPartOfCitation(){var evidence=new EvidenceReference("ev-realtime-50d1d73c-6b89-46f2-a281-9cc39e522c1b","FUND_REALTIME_QUOTE","004069",null,null,null,"eastmoney-push2",null,null,null);String answer=policy.validateAndRepair("涨跌幅 +0.29% ev-realtime-50d1d73c-6b89-46f2-a281-9cc39e522c1b---\n",List.of(evidence));assertThat(answer).contains(evidence.evidenceId()+"---");}
    @Test void preservesMarkdownLineBreaksWhileRepairing(){var evidence=new EvidenceReference("ev-sector-1","FUND_SECTOR_OUTLOOK","562500",null,null,null,"tencent-qt",null,null,null);String answer=policy.validateAndRepair("## 情景分析\n\n- 近20日涨跌 -2.01%\n- 基准情景\n",List.of(evidence));assertThat(answer).contains("## 情景分析\n\n- 近20日涨跌").contains("\n- 基准情景\n");}
    @Test void announcementClaimAcceptsVerifiedEventEvidence(){var evidence=new EvidenceReference("ev-event-1","COMPANY_ANNOUNCEMENT","562500",null,null,null,"exchange-announcement",null,null,null);String answer=policy.validateAndRepair("重仓股发布回购公告，构成可核验利好 ev-event-1。",List.of(evidence));assertThat(answer).contains("ev-event-1");}
    @Test void managerIdentityIsNotMisclassifiedAsARequiredDocumentClaim(){var evidence=new EvidenceReference("ev-profile-1","FUND_PROFILE","011612",null,null,null,"eastmoney-public",null,null,null);String answer=policy.validateAndRepair("基金经理为荣膺。",List.of(evidence));assertThat(answer).isEqualTo("基金经理为荣膺。");}
    @Test void mixedHoldingAndAnnouncementClaimAcceptsBothEvidenceTypes(){var holding=new EvidenceReference("ev-holding-1","FUND_HOLDING","562500",null,null,null,"fund-holding",null,null,null);var announcement=new EvidenceReference("ev-event-1","COMPANY_ANNOUNCEMENT","562500",null,null,null,"exchange-announcement",null,null,null,null,null,null,"以集中竞价方式回购公司股份进展公告",null,null,null,null,null,null);String answer=policy.validateAndRepair("中控技术回购是明确利好（6.35%） ev-holding-1。",List.of(holding,announcement));assertThat(answer).contains("ev-holding-1").contains("ev-event-1");}
    @Test void marketAnswerMentioningEventsDoesNotFailWithoutDocuments(){var evidence=new EvidenceReference("ev-sector-1","FUND_SECTOR_OUTLOOK","159303",null,null,null,"tencent-qt",null,null,null);String answer=policy.validateAndRepair("近20日涨跌 -2.75%。未发现可核验的重大事件，后续仍需跟踪公告。",List.of(evidence));assertThat(answer).contains("ev-sector-1").contains("-2.75%");}
    @Test void dataVersionDigitsAreNotTreatedAsASeparateFundCode(){var evidence=new EvidenceReference("ev-sector-1","FUND_SECTOR_OUTLOOK","159303",null,null,null,"tencent-qt",null,null,null);String answer=policy.validateAndRepair("数据版本为20260924161451。",List.of(evidence));assertThat(answer).isEqualTo("数据版本为20260924161451。");}
    @Test void drawdownAnswerWithMetricsEvidenceIsNotRejected(){var evidence=new EvidenceReference("ev-metrics-8f3e2c1a-6b89-46f2-a281-9cc39e522c1b","FUND_METRICS","460300",LocalDate.of(2025,9,25),LocalDate.of(2026,9,24),"UNIT_NAV","fund-nav","3","fund-metrics-v1",null);String raw="根据工具计算结果，华泰柏瑞沪深300ETF联接A（460300）在近一年区间（2025-09-25 至 2026-09-24）的最大回撤为 -18.72%（即 -0.1872）。\n实际数据区间：2025-09-25 至 2026-09-24（共243个观测日）。\n数据版本：fund-metrics-v1 / ev-metrics-8f3e2c1a-6b89-46f2-a281-9cc39e522c1b。\n局限性提示：数据覆盖率状态为 UNKNOWN；以上指标仅反映历史表现，不代表未来收益或风险水平。";String answer=policy.validateAndRepair(raw,List.of(evidence));assertThat(answer).contains("-18.72%").contains(evidence.evidenceId());}
}
