package com.jijing.fund.knowledge.service;

import com.jijing.fund.knowledge.domain.*;
import com.jijing.fund.knowledge.port.*;
import java.time.*;
import java.util.*;

/** Executes one leased job and restores durable parse/chunk/embedding checkpoints after a crash. */
public final class KnowledgeIngestionProcessor {
    private final DocumentMetadataRepository metadata;private final KnowledgeJobRepository jobs;private final KnowledgeCheckpointStore checkpoints;
    private final RawDocumentStore rawStore;private final DocumentParser parser;private final ChineseDocumentChunker chunker;
    private final DocumentEmbeddingPort embeddings;private final DocumentSearchIndex index;private final Clock clock;
    private final String parserVersion,chunkingVersion;private final int embeddingBatchSize;
    public KnowledgeIngestionProcessor(DocumentMetadataRepository metadata,KnowledgeJobRepository jobs,KnowledgeCheckpointStore checkpoints,RawDocumentStore rawStore,DocumentParser parser,ChineseDocumentChunker chunker,DocumentEmbeddingPort embeddings,DocumentSearchIndex index,Clock clock,String parserVersion,String chunkingVersion,int embeddingBatchSize){this.metadata=metadata;this.jobs=jobs;this.checkpoints=checkpoints;this.rawStore=rawStore;this.parser=parser;this.chunker=chunker;this.embeddings=embeddings;this.index=index;this.clock=clock;this.parserVersion=parserVersion;this.chunkingVersion=chunkingVersion;this.embeddingBatchSize=Math.max(1,embeddingBatchSize);}
    public void process(KnowledgeJobWorkItem item){IngestionStatus current=resumeStatus(item.lastCompletedStep());try{
        ParsedDocument parsed=null;List<DocumentChunk>chunks=null;List<float[]>vectors=new ArrayList<>();
        if(current==IngestionStatus.REGISTERED){rawStore.read(item.storageKey());current=move(item.versionId(),current,IngestionStatus.FETCHED);jobs.checkpoint(item.jobId(),"FETCHED",0,0,clock.instant());}
        if(current==IngestionStatus.FETCHED){current=move(item.versionId(),current,IngestionStatus.PARSING);parsed=parser.parse(item.contentType(),item.originalFileName(),rawStore.read(item.storageKey()));if(parsed.textCharacters()==0){metadata.transition(item.versionId(),current,IngestionStatus.OCR_REQUIRED,clock.instant());jobs.releaseFailure(item.jobId(),IngestionStatus.OCR_REQUIRED,"OCR_REQUIRED","Document has no extractable text",null,clock.instant());return;}checkpoints.saveParsed(item.versionId(),parsed);metadata.updateParsed(item.versionId(),parsed.pages().size(),parsed.textCharacters(),parserVersion,parsed.warnings(),clock.instant());current=move(item.versionId(),current,IngestionStatus.PARSED);jobs.checkpoint(item.jobId(),"PARSED",0,0,clock.instant());}
        if(current==IngestionStatus.PARSED){if(parsed==null)parsed=checkpoints.loadParsed(item.versionId());current=move(item.versionId(),current,IngestionStatus.CHUNKING);var context=new ChunkingContext(item.documentId(),item.versionId(),item.title(),item.documentType(),item.publishedDate(),item.fundCodes(),item.sourceName(),item.sourceUri(),chunkingVersion);chunks=chunker.split(parsed,context);if(chunks.isEmpty())throw new IllegalArgumentException("No searchable text chunks were produced");checkpoints.saveChunks(item.versionId(),chunks);metadata.replaceChunkMetadata(item.versionId(),chunks,"artifacts/"+item.versionId()+"/chunks.json",clock.instant());current=move(item.versionId(),current,IngestionStatus.CHUNKED);jobs.checkpoint(item.jobId(),"CHUNKED",0,0,clock.instant());}
        if(current==IngestionStatus.CHUNKED||current==IngestionStatus.EMBEDDING){if(chunks==null)chunks=checkpoints.loadChunks(item.versionId());int completed=current==IngestionStatus.EMBEDDING?item.embeddedBatchNo():0;if(completed>0)vectors.addAll(checkpoints.loadEmbeddingBatches(item.versionId(),completed));if(current==IngestionStatus.CHUNKED)current=move(item.versionId(),current,IngestionStatus.EMBEDDING);int start=completed*embeddingBatchSize;for(int from=start;from<chunks.size();from+=embeddingBatchSize){int to=Math.min(chunks.size(),from+embeddingBatchSize);List<float[]>batch=embeddings.embed(chunks.subList(from,to).stream().map(DocumentChunk::content).toList());if(batch.size()!=to-from)throw new IllegalStateException("EMBEDDING_COUNT_MISMATCH");int batchNo=from/embeddingBatchSize+1;checkpoints.saveEmbeddingBatch(item.versionId(),batchNo,batch);vectors.addAll(batch);jobs.checkpoint(item.jobId(),"EMBEDDING",batchNo,0,clock.instant());}current=move(item.versionId(),current,IngestionStatus.INDEXING);}
        if(current==IngestionStatus.INDEXING){if(chunks==null)chunks=checkpoints.loadChunks(item.versionId());if(vectors.isEmpty())vectors.addAll(checkpoints.loadEmbeddingBatches(item.versionId(),Math.max(item.embeddedBatchNo(),batches(chunks.size()))));if(vectors.size()!=chunks.size())throw new IllegalStateException("EMBEDDING_COUNT_MISMATCH");List<IndexedChunk>values=new ArrayList<>(chunks.size());for(int i=0;i<chunks.size();i++)values.add(new IndexedChunk(chunks.get(i),vectors.get(i),embeddings.version()));index.index(values);jobs.checkpoint(item.jobId(),"INDEXING",batches(chunks.size()),values.size(),clock.instant());index.activate(item.documentId(),item.versionId());metadata.updateIndexed(item.versionId(),chunks.size(),chunkingVersion,embeddings.version(),index.indexVersion(),clock.instant());current=move(item.versionId(),current,IngestionStatus.READY);jobs.checkpoint(item.jobId(),"READY",batches(chunks.size()),chunks.size(),clock.instant());jobs.releaseSuccess(item.jobId(),clock.instant());}
      }catch(RuntimeException error){Failure f=classify(error,item.attemptCount());metadata.fail(item.versionId(),item.jobId(),f.status(),f.code(),safe(error),clock.instant());jobs.releaseFailure(item.jobId(),f.status(),f.code(),safe(error),f.nextRetryAt(),clock.instant());}}
    private int batches(int chunks){return (chunks+embeddingBatchSize-1)/embeddingBatchSize;}private IngestionStatus move(String id,IngestionStatus from,IngestionStatus to){metadata.transition(id,from,to,clock.instant());return to;}
    private IngestionStatus resumeStatus(String value){if(value==null||value.isBlank())return IngestionStatus.REGISTERED;try{return IngestionStatus.valueOf(value);}catch(Exception e){return IngestionStatus.REGISTERED;}}
    private Failure classify(RuntimeException error,int attempts){String text=(error.getMessage()==null?"":error.getMessage()).toUpperCase(Locale.ROOT);if(text.contains("UNSUPPORTED")||text.contains("NO SEARCHABLE")||text.contains("CORRUPT")||text.contains("CHECKPOINT"))return new Failure(IngestionStatus.FAILED_FINAL,"INVALID_DOCUMENT",null);if(text.contains("DIMENSION"))return new Failure(IngestionStatus.FAILED_FINAL,"EMBEDDING_DIMENSION_MISMATCH",null);if(attempts>=3)return new Failure(IngestionStatus.FAILED_FINAL,"RETRY_EXHAUSTED",null);long delay=Math.min(600,10L<<Math.min(5,attempts));return new Failure(IngestionStatus.FAILED_RETRYABLE,text.contains("ELASTIC")?"ELASTICSEARCH_UNAVAILABLE":"KNOWLEDGE_DEPENDENCY_UNAVAILABLE",clock.instant().plusSeconds(delay));}
    private String safe(Throwable error){String value=error.getMessage()==null?error.getClass().getSimpleName():error.getMessage();return value.substring(0,Math.min(500,value.length()));}private record Failure(IngestionStatus status,String code,Instant nextRetryAt){}
}
